from datetime import datetime

from sqlalchemy import String, DateTime, Integer, Text
from sqlalchemy.orm import Mapped, mapped_column

from backend.database import Base


class Alert(Base):
    """Rule-based alerts generated by the signal engine."""
    __tablename__ = "alerts"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    rule: Mapped[str] = mapped_column(String, index=True)  # e.g. "floating_storage"
    zone: Mapped[str] = mapped_column(String, default="")
    severity: Mapped[str] = mapped_column(String)  # "info", "warning", "critical"
    title: Mapped[str] = mapped_column(String)
    detail: Mapped[str] = mapped_column(Text, default="")
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
